### ISSUE TITLE
Consider using 2.3.0 as ruby version since that is what rbenv uses

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cf-mysql-release#109]
```
> rbenv install
ruby-build: definition not found: 2.3

The following versions contain `2.3' in the name:
  2.2.3
  2.3.0-dev
  2.3.0-preview1
  2.3.0-preview2
  2.3.0
  2.3.1
  rbx-2.2.3
  rbx-2.3.0

See all available versions with `rbenv install --list'.
```

**Comment by mfine30** [comment]
Hi @youngm, 

I believe that you are referring to the cf-mysql-broker Ruby code? We have updated the broker application to use Ruby 2.3.1 in its Gemfile for a recent [CVE](https://www.pivotaltracker.com/story/show/128688905). I'm going to close this since I can see that 2.3.1 is in the list of rubies that rbenv knows about. Please feel free to open another issue if this is still a problem.

Best,
Morgan
