### ISSUE TITLE
Enabling syslog doesn't appear to send mysql.err.log to syslog

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cf-mysql-release#116]
I'm running develop commit: https://github.com/cloudfoundry/cf-mysql-release/tree/573340a561992d60e7ca067c1e2eab89c067d0ce

When I enable syslog many things get sent to syslog like mariadb_ctrl but I don't appear to get any actual mysql log messages like the following I found in mysql.err.log
```
InnoDB: Completed initialization of buffer pool
```

Looking at the logs I see a message:
```
mysqld_safe Can't log to error log and syslog at the same time.  Remove all --log-error configuration options for --syslog to take effect.
```

If I remove "log-error" from my.cnf then I see some mysql log messages like the one above in syslog.

**Comment by mfine30** [comment]
Hi @youngm,

Thank you for opening this issue. We have updated the develop branch of cf-mysql to correct the issue. The next release, v27, should have it. For now, either the `develop` or `release-candidate` branches contain the fix.

I'm going to close this since it will make it into the next release.

Thanks,
Morgan
