### ISSUE TITLE
Adding timezone support

### ISSUE THREAD

**Issue by ysholqamy** [cloudfoundry/cf-mysql-release#119]
Hello, how can I add tzinfo to a mysql service instance?

**Comment by mfine30** [comment]
Hi @ysholqamy,

It looks like `tzinfo` is a program to generate SQL statements to load your time zone tables. Looking at the documentation for `mysql_tzinfo_to_sql` at https://dev.mysql.com/doc/refman/5.5/en/mysql-tzinfo-to-sql.html, it looks like you will need to modify the `mysql` system database. This is something that can't be done at the service instance level; it requires root access and is on a per-deployment basis. I would suggest talking to the operator of your deployment about this. 

Assuming you talk to them, it looks like you can run this command to update the database
```
$ mysql_tzinfo_to_sql /usr/share/zoneinfo | mysql -u root -p -hHOST --database=mysql
```

Best,
Morgan
CF Core Services

**Comment by GETandSELECT** [comment]
Hello @menicosia 

can you integrate time zone support in bosh release? We don't wish to this manual. A customer of us also ask for this.

The command @mfine30 posted needs to be run on every cluster node because of https://jira.mariadb.org/browse/MDEV-11653 (replication of MyISAM tables broken).

@ysholqamy please reopen this issue. Thanks.

Thank you
