### ISSUE TITLE
How to apply max_connect_errors, wait_timeout, interactive_timeout to mysql?

### ISSUE THREAD

**Issue by YunSangJun** [cloudfoundry/cf-mysql-release#136]
I applied follows to mysql manifest file but it did not apply to "my.cnf".

...
properties:
...
   cf_mysql:
      ...
      mysql:
         max_connect_errors :
         wait_timeout : 
         interactive_timeout :

**Comment by menicosia** [comment]
Hi @YunSangJun,

Sorry for the long delay, this issue got lost in the shuffle.

Currently, not all `mysql` configurables are accessible through the manifest. You can see all of the job configuration in the [spec file](http://bosh.io/jobs/mysql?source=github.com/cloudfoundry/cf-mysql-release).

Cf-mysql-release is constrained in that way so that the number of use cases we have to support is similarly constrained. But we are certainly open to making additional tunables available in coming releases. I'd like to know what you're trying to accomplish - it will help to understand why a particular configuration property is necessary.

In particular, `max_connect_errors` is a problem for cf-mysql-release, because what frequently happened was that a misbehaving app results in the MySQL nodes blacklisting the proxy, taking all clients down. We solve this problem by turning of reverse host lookups, which effectively disables the blacklisting feature.

Let us know your thoughts, and again, sorry for the delay!

--

  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by robdimsdale** [comment]
We're going to close this now as there's been no response in a month. Please feel free to reopen with any thoughts.
