### ISSUE TITLE
smoke_tests should specify domain when pushing cf app

### ISSUE THREAD

**Issue by poblin-orange** [cloudfoundry/cf-mysql-release#137]
We have issue while running the smoke_tests on a multiple domains cf deployment.
The assertion on running app (curl -k ...)  uses a specific cf domain, whereas the cf push instruction does not specify the target domain, resulting in cf app mapped to default domain.

see https://github.com/cloudfoundry-incubator/cf-mysql-acceptance-tests/blob/master/cf-mysql-service/lifecycle/lifecycle_test.go#L35

```


P-MySQL Lifecycle Tests
/var/vcap/packages/acceptance-tests/src/github.com/cloudfoundry-incubator/cf-mysql-acceptance-tests/cf-mysql-service/lifecycle/lifecycle_test.go:81
  Allows users to create, bind, write to, read from, unbind, and destroy a service instance for the each plan [It]
  /var/vcap/packages/acceptance-tests/src/github.com/cloudfoundry-incubator/cf-mysql-acceptance-tests/cf-mysql-service/lifecycle/lifecycle_test.go:60

  Got stuck at:
      404 Not Found: Requested route ('xxxxxxxxxxxxxxxxxxxxxxxxxxxxx') does not exist. 

```
 cc / @szaouam

**Comment by menicosia** [comment]
Hi @poblin-orange,

Sorry it took us so long to get to this. We've committed the changes necessary to address your issue. You should be able to see your change on the `develop` branch. Please let us know if this works for you, ideally before we ship cf-mysql-release v33, otherwise, additional fixes will likely have to wait till the next release.

We're going to close this issue for now, please feel free to re-open.

--

Marco Nicosia
Product Manager
