### ISSUE TITLE
Unused nats properties

### ISSUE THREAD

**Issue by wendorf** [cloudfoundry/cf-mysql-release#157]
proxy and cf-mysql-broker jobs still have nats properties, and manifest-generation yml files still include them, but the release doesn't use nats anymore.

Also, there's no mention in the README that this has changed and that route_registrar needs to be co-located.

**Comment by jpalermo** [comment]
We've removed the properties from the spec files but have left them in the manifest generation since they are still required for the routing release.

The routing release prerequisite has been in the readme for 3 months:
https://github.com/cloudfoundry/cf-mysql-release/blob/develop/README.md#prerequisites-1
