### ISSUE TITLE
Why SST is disabled by default "disable_auto_sst: true"? What are the reasons for this?

### ISSUE THREAD

**Issue by GETandSELECT** [cloudfoundry/cf-mysql-release#165]
Hello

1 node (from 3) was failing for unknown reason, see [mysql error logs](https://gist.github.com/00ab731e7cb5c57a5edbb4e20074aae6) 

The problem was fixed with [this steps](https://github.com/pivotal-cf/docs-mysql/blob/master/monitoring-mysql.html.md.erb#L145-L152).

bosh run errand [rejoin-unsafe didn't work](https://gist.githubusercontent.com/anonymous/d13dbf8508e7e80d6edfe01b61a7e442/raw/b6efbba2c941e3a068fef3b5d3cda246fc714437/gistfile1.txt) 

Why did you disable SST in bosh release? What is the exact reason? This issue would have been solved without Operator intervention if SST not disabled.

What could go wrong when we enable SST in deployment manifest?

Do you cf-mysql-release developers also read Stack Overflow? Maybe StackOverflow #cloudfoundry better place for this question?

**Comment by utricularian** [comment]
The `Defensive Enhancements`section in the [v27](https://github.com/cloudfoundry/cf-mysql-release/releases/tag/v27) release notes describe the reasoning behind disabling the SST. Since then, we've added more sophisticated features to mitigate the problems we found back in v27. Setting `disable_auto_sst` to false should be perfectly fine for all but the most paranoid of users.

We have plans in the near future to flip the default to allow SST.
