### ISSUE TITLE
verify-cluster-schemas (and possibly others) don't work with remote_admin_access=false

### ISSUE THREAD

**Issue by youngm** [cloudfoundry/cf-mysql-release#172]
It appears that errand uses root by default.

If we need to use a different user, then some instructions on how to create another user with the correct permissions to the errands would be helpful.

**Comment by menicosia** [comment]
Thanks, I've created [#148683645](https://www.pivotaltracker.com/story/show/148683645) to address this. Depending on how important this turns out to be, it may be scheduled for cf-mysql-release v37.

I've added a [known issue](https://github.com/cloudfoundry/cf-mysql-release/commit/fe3a9dd2dac74971c89cf358068184a115b326d0) for v36.

I'll go ahead and close this issue, and you can track the fix in the story mentioned above. If there's a further issue, of course you're welcome to re-open this issue or create a new one.

Thanks @youngm !

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by youngm** [comment]
Thanks @menicosia We'll just set that property to `true` for now like it was before.  So, no need to rush a fix in on our account. :)  Thanks.
