### ISSUE TITLE
Allow extra parameters to be merged into the resource pool items

### ISSUE THREAD

**Issue by cromega** [cloudfoundry/cf-mysql-release#78]
As cf-mysql-template.yml is right now there are only hacky ways of getting some extra stuff, such as sudo password to be merged into the deployment manifest.

**Comment by menicosia** [comment]
Hey @cromega,

Can you give us a better understanding about your request? We're having a hard time following what you mean by, "merged into the resource pool items."

I think maybe this request is more about manifest generation (which is not specifically a cf-mysql-release functionality) than a feature request about the mysql bosh release?

--
Marco Nicosia
Product Manager
PIvotal Software, Inc.

**Comment by menicosia** [comment]
Hey @cromega,

Since you haven't had a chance to update this issue, and there aren't direct requests I can think about here, I'm going to go ahead and close this issue.

If you come back and want to pick up the discussion again, please feel free to re-open the issue! Our bot will drop it back into our queue, so we should see the update.

--
Marco Nicosia
Product Manager
PIvotal Software, Inc.
