### ISSUE TITLE
bosh deploy error : no implicit conversion of Fixnum into String 

### ISSUE THREAD

**Issue by liuxiaoxi2237** [cloudfoundry/cf-mysql-release#80]
Hi Expert,
When run bosh deploy, I got below issue:
bosh  1.3016.0
ruby 2.1.6
mysql release 22

-----------------------------
Deploying
---------
Are you sure you want to deploy? (type 'yes' to continue): yes

Director task 63
  Started unknown
  Started unknown > Binding deployment. Done (00:00:00)

  Started preparing deployment
  Started preparing deployment > Binding releases. Done (00:00:00)
  Started preparing deployment > Binding existing deployment. Done (00:00:00)
  Started preparing deployment > Binding resource pools. Done (00:00:00)
  Started preparing deployment > Binding stemcells. Done (00:00:01)
  Started preparing deployment > Binding templates. Done (00:00:00)
  Started preparing deployment > Binding properties. Done (00:00:00)
  Started preparing deployment > Binding unallocated VMs. Done (00:00:00)
  Started preparing deployment > Binding instance networks. Done (00:00:00)

  Started preparing package compilation > Finding packages to compile. Done (00:00:00)

  Started compiling packages
  Started compiling packages > cli/24305e50a638ece2cace4ef4803746c0c9fe4bb0
  Started compiling packages > mysqlclient/ce95f8ac566f76b650992987d5282ee473356e43
  Started compiling packages > ruby/ff79c965224b4160c1526bd704b3b21e4ad7c362
  Started compiling packages > syslog_aggregator/078da6dcb999c1e6f5398a6eb739182ccb4aba25
   Failed compiling packages > cli/24305e50a638ece2cace4ef4803746c0c9fe4bb0: no implicit conversion of Fixnum into String (00:00:00)
   Failed compiling packages > syslog_aggregator/078da6dcb999c1e6f5398a6eb739182ccb4aba25: no implicit conversion of Fixnum into String (00:00:00)
   Failed compiling packages > mysqlclient/ce95f8ac566f76b650992987d5282ee473356e43: no implicit conversion of Fixnum into String (00:00:00)
   Failed compiling packages > ruby/ff79c965224b4160c1526bd704b3b21e4ad7c362: no implicit conversion of Fixnum into String (00:00:00)
----------------------------------------
Thanks,
David

**Comment by ljfranklin** [comment]
@liuxiaoxi2237 I'm guessing you are deploying on vsphere. If you look at your manifest under `compilation.cloud_properties.{ram,disk,cpu}` are the numbers in quotes? Newer versions of bosh will error on quoted numbers in resource configs. We've since fixed this in our [develop](https://github.com/cloudfoundry/cf-mysql-release/commit/1e3b88865d69f0058b269fc47a17b00c05872f70) branch and are planning on cutting a new release within the next week or so which will include the fix. In the meantime, you can edit your manifest to remove the quotes in all the `cloud_property` sections.

**Comment by liuxiaoxi2237** [comment]
Yes, that is the root cause. Thank you so much!
