### ISSUE TITLE
cloud foundry

### ISSUE THREAD

**Issue by lagask** [cloudfoundry/cf-mysql-release#98]
hello to all
I have a problem when I try to bind laravel app to p-mysql service created, I get connection refused error and app deployment failed. 
what I tried to do:
1. use cf-laravel-example instead of my application still not working
2. I can access service instance of p-mysql 
3. delete service and create, bind it again to the app.

I am using cf-release 231, cf-mysql-release 26 

**BINDING INFO**
```json
{
 "VCAP_SERVICES": {
  "p-mysql": [
   {
    "credentials": {
     "hostname": "10.244.7.6",
     "jdbcUrl": "jdbc:mysql://10.244.7.6:3306/cf_13b087f4_9531_4550_bd20_9eb7952b0d22?user=WFUTfD2qic1hrXII\u0026password=5YBedtOkQuqB24GV",
     "name": "cf_13b087f4_9531_4550_bd20_9eb7952b0d22",
     "password": "5YBedtOkQuqB24GV",
     "port": 3306,
     "uri": "mysql://WFUTfD2qic1hrXII:5YBedtOkQuqB24GV@10.244.7.6:3306/cf_13b087f4_9531_4550_bd20_9eb7952b0d22?reconnect=true",
     "username": "WFUTfD2qic1hrXII"
    },
    "label": "p-mysql",
    "name": "lagask",
    "plan": "100mb",
    "provider": null,
    "syslog_drain_url": null,
    "tags": [
     "mysql"
    ]
   }
  ]
 }
}
```

**The Error am getting**

Writing lock file
Generating autoload files
Generating optimized class loader
Compiling common classes
  [PDOException]                             
  SQLSTATE[HY000] [2002] Connection refused  
Script php htdocs/artisan migrate --force handling the post-install-cmd event returned with an error
  [RuntimeException]

**Comment by menicosia** [comment]
Hi @lagask,

Please post a **redacted** version of your manifest, I suggest using [gist](gist.github.com) rather than pasting all the text directly into this issue.

The URI that the service is providing you to access MySQL is using the standard port, `3306`. Thus, it seems likely that something between your application service container and MySQL is blocking your connection.

1. Are you deploying in a minimal configuration, or in an HA configuration? In HA, you're expected to provide a load balancer above the Proxies, that could be the source of the block.
1. Is there something in your network that prevents connections to the MySQL IPs? Do you have network-local access to the MySQL VMs? You can use a [service key](http://docs.cloudfoundry.org/devguide/services/service-keys.html) to try connecting directly to diagnose the nature of your connectivity issue.
1. Perhaps you have an [Application Security Group](http://docs.cloudfoundry.org/adminguide/app-sec-groups.html) deployed as part of your greater Cloud Foundry deployment which is not allowing the containers to make connections to the MySQL IPs.

Hope this helps,

--
  Marco Nicosia
  Product Manager
  Pivotal Software, Inc.

**Comment by lagask** [comment]
sorry for late reply it was crazy at work.


I have local access I can ssh and log on to mysql instance.  and
When I ran **cf service-access**

I GOT

Getting service access as admin... broker: p-mysql service plan access orgs
p-mysql 100mb all
p-mysql 1gb all

I'm using bosh lite on my laptop (cloud foundry local deployment)

**Comment by aditya87** [comment]
Hi lagask,

Please post a redacted version of your cf-mysql manifest using gist to help us debug this issue better. Also, can you try "cf create-service-key" and tell us what you get?

Thanks,
-Adi
CF Core Services

**Comment by menicosia** [comment]
Hi!

We haven't heard back from you in about a week, so we'll close this issue for now. Of course, if you're still having the problem, please feel free to post a redacted version of your manifest and re-open this issue. We'll be happy to look into it again in the future.

--
Marco Nicosia
Product Manager
Pivotal Software, Inc.
