### ISSUE TITLE
Problem when generate-bosh-manifest

### ISSUE THREAD

**Issue by vfonsecapv** [cloudfoundry/cf-mysql-release#99]
Hi guys, when I try to generate bosh lite manifest, get this error:

> 2016/04/05 17:58:33 error generating manifest: unresolved nodes:
	(( merge || "30000-" canary_end_in_sec ))	in /Users/victorfonseca/workspace/cf-mysql-release/manifest-generation/cf-mysql-template.yml	update.canary_watch_time	()
	(( merge || "30000-" canary_end_in_sec ))	in /Users/victorfonseca/workspace/cf-mysql-release/manifest-generation/cf-mysql-template.yml	update.update_watch_time	()
	(( "" .properties.cf_mysql.mysql.database_startup_timeout ))	in /Users/victorfonseca/workspace/cf-mysql-release/manifest-generation/cf-mysql-template.yml	database_startup_timeout_str	()
	(( database_startup_timeout_str "000" ))	in /Users/victorfonseca/workspace/cf-mysql-release/manifest-generation/cf-mysql-template.yml	canary_end_in_sec	()
2016/04/05 17:58:33 error parsing stub [/tmp/mysql_manifest.c3a1A/mysql-config.yml]: Expected document start at line 0, column 0
victorfonseca@victor32:~/workspace/cf-mysql-release$ ./scripts/generate-bosh-lite-manifest ./manifest-generation/bosh-lite-stubs/cf-manifest.yml 

Any ideas?

**Comment by mfine30** [comment]
Hi @vfonsecapv,

Could you please let us know what version of cf-mysql-release you are using? Also, what version of `spiff` do you have installed on your machine? 

Thanks,
Morgan and Adi
CF Core Services

**Comment by vfonsecapv** [comment]
release 26. spiff-1.0.6

**Comment by vfonsecapv** [comment]
I install spiff 1.0.7 and works. I don't know why. Any idea?

**Comment by mfine30** [comment]
If you look at the top line of your stack trace, you can see there is a line that says we are trying to evaluate `(( merge || "30000-" canary_end_in_sec ))`. Since the bosh-lite manifest generation doesn't use an override, we evaluate the second half, `"30000-" canary_end_in_sec`. Running this requires concatenating a string with an integer, a feature that was not introduced until [spiff 1.0.7](https://github.com/cloudfoundry-incubator/spiff/releases/tag/v1.0.7)
